_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 79
                - 83
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 79
                - 83
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.7
            "6": 4.30.2
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.01
allow_tf32:
    value: false
checkpointing_steps:
    value: 4000
checkpoints_total_limit:
    value: null
compute_metrics:
    value: false
cond_lighting_index:
    value: 0
conditioning_dropout_prob:
    value: 0.05
dataloader_num_workers:
    value: 4
enable_xformers_memory_efficient_attention:
    value: true
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
guidance_scale:
    value: 3
hub_model_id:
    value: null
hub_token:
    value: null
learning_rate:
    value: 0.0001
lighting_dir:
    value: ./preprocessed_lighting_data
lighting_per_view:
    value: 4
logging_dir:
    value: logs
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant_with_warmup
lr_warmup_steps:
    value: 100
max_grad_norm:
    value: 1
max_train_steps:
    value: 80000
mixed_precision:
    value: fp16
num_train_epochs:
    value: 114
num_validation_batches:
    value: 230400
num_validation_images:
    value: 1
output_dir:
    value: logs/03_09_finetune_zero123xl_with_preprocessed_data
pretrained_model_name_or_path:
    value: kxic/zero123-xl
push_to_hub:
    value: false
report_to:
    value: wandb
resolution:
    value: 256
resume_from_checkpoint:
    value: latest
revision:
    value: null
save_dir:
    value: ./
scale_lr:
    value: false
seed:
    value: 42
set_grads_to_none:
    value: true
specific_object:
    value: -1
total_view:
    value: 120
tracker_project_name:
    value: train_neural_gaffer_private
train_batch_size:
    value: 64
train_data_dir:
    value: /home/hj453/code/zero123-hf/original_real_input/
use_8bit_adam:
    value: false
use_ema:
    value: true
validation_data_dir:
    value: ./Neural_Gaffer/preprocessed_data
validation_steps:
    value: 2000
